services:
  es01:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: es01
    ports:
      - 9200:9200
      - 9300:9300

    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
